spring:
  application:
    name: MyList
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mysecretpassword
    platform: PostgreSQL
  jpa:
    hibernate:
      ddl-auto: none
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    show-sql: true
  flyway:
    enabled: true
    schemas: public

server:
  port: 9081

---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test
    platform: H2
