spring:
  application:
    name: MyList
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: sa
    platform: H2
  jpa:
    hibernate:
      ddl-auto: update
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    show-sql: true

server:
  port: 9081

---

spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://192.168.99.100:5432/postgres
    username: postgres
    password: start123
    platform: POSTGRESQL
